---

- name: Apply static resources
  kubernetes.core.k8s:
    state: "{{ item.state | default('present', true) }}"
    name: "{{ item.name | default(omit, true) }}"
    definition: "{{ item.definition | default(omit, true) }}"
    src: "{{ item.src | default(omit, true) }}"
    template: "{{ item.template | default(omit, true) }}"
    namespace: "{{ item.namespace | default(omit, true) }}"
    wait: "{{ item.wait | default(omit, true) }}"
    wait_condition: "{{ item.wait_condition | default(omit, true) }}"
    wait_timeout: "{{ item.wait_timeout | default(omit, true) }}"
    wait_sleep: "{{ item.wait_sleep | default(omit, true) }}"
    force: "{{ item.force | default(omit, true) }}"
  loop: "{{ static_resources }}"
  loop_control:
    label: "{{ item.definition.metadata.name if item.definition is defined else item.name | default('kubernetes resource', true) }}"
