---
# Install and configure Multus CNI for VLANs

- name: Download Multus CNI manifest
  ansible.builtin.get_url:
    url: https://raw.githubusercontent.com/k8snetworkplumbingwg/multus-cni/master/deployments/multus-daemonset-thick.yml
    dest: /tmp/.talos/multus-daemonset.yml

- name: Replace /run/netns/ with /var/run/netns/ in Multus manifest
  ansible.builtin.replace:
    path: /tmp/.talos/multus-daemonset.yml
    regexp: '/run/netns/'
    replace: '/var/run/netns/'

- name: Apply Multus CNI manifest
  kubernetes.core.k8s:
    src: /tmp/.talos/multus-daemonset.yml
    state: present

- name: Patch Multus DaemonSet to install cni plugins
  kubernetes.core.k8s:
    kind: DaemonSet
    namespace: kube-system
    name: kube-multus-ds
    state: patched
    definition:
      spec:
        template:
          spec:
            initContainers:
              - name: install-cni-plugins
                image: rancher/hardened-cni-plugins:v1.8.0-build20250909 # pin to a current tag
                securityContext:
                  privileged: true
                env:
                  - name: UPDATE_CNI_BINARIES
                    value: "false"
                  - name: SKIP_CNI_BINARIES
                    value: "flannel,firewall"
                volumeMounts:
                  - name: cnibin
                    mountPath: /host/opt/cni/bin
                    mountPropagation: Bidirectional

- name: Ensure all multus pods are running
  kubernetes.core.k8s_info:
    kind: Pod
    namespace: kube-system
    label_selectors:
      - app=multus
  register: pod_list
  until: pod_list|json_query('resources[*].status.phase')|unique == ["Running"]
  retries: 30
  delay: 6

# Commented out for now, because you want to create the network attachment definitions in the corresponding namespace
# Thus it makes more sense to do this either via the argocd app-of-apps or via static resources

# - name: Create Multus network attachment definitions for VLANs
#   ansible.builtin.template:
#     src: multus_vlan_network.yaml.j2
#     dest: /tmp/.talos/multus_vlan_{{ vlan.name }}.yaml
#   loop: "{{ vlan_config }}"
#   loop_control:
#     loop_var: vlan
#     label: "{{ vlan.name }} - {{ vlan.vlan_id }} - {{ vlan.type }} - {{ vlan.address if vlan.type == 'static' else vlan.subnet }}"

# - name: Apply Multus VLAN network attachments
#   kubernetes.core.k8s:
#     state: present
#     src: /tmp/.talos/multus_vlan_{{ vlan.name }}.yaml
#   loop: "{{ vlan_config }}"
#   loop_control:
#     loop_var: vlan
#     label: "{{ vlan.name }} - {{ vlan.vlan_id }} - {{ vlan.type }} - {{ vlan.address if vlan.type == 'static' else vlan.subnet }}"
